### ISSUE TITLE
Throw error if a resource is inserted without any valid labels

### ISSUE THREAD

**Issue by RPGHacker** [Fernap/UberASMTool#10]
I have a specific problem that has been driving me nuts for what must have been weeks by now, and by this point I'm questioning if I'm just getting something incredibly simple wrong.

Recently, I tried to integrate UberASM Tool 2.0 into my personal build system. Previously, I just used the old standalone UberASM patch for this and it's been working fine for me. However, I can't, for the love of god, get UberASM Tool to work to the same outcome. First of all, here is one version of my generated list.txt file (and I actually tried many different versions, all to the same result):

![grafik](https://github.com/user-attachments/assets/1d46a9bd-690e-42a0-953f-0c3821fccbf3)

And here is the output of UberASM Tool when using that list.txt:
![grafik](https://github.com/user-attachments/assets/96a5f101-e91b-4f18-bcdb-d6d8d802b91c)

And the .asm files I tried inserting simply contain this (because I literally just wanted anything visible to happen in the game):
```
stp
brk #$00
```

I can confirm that, just like UberASM Tool is claiming, the .asm files **were** inserted into the game. Confirmed this by putting a magic byte sequence into one of my .asm files and then searching the ROM file for it in a hex editor. However, despite the .asm files being inserted, the game just refuses to execute them. Neither do I encounter that `stp` in any game mode, nor in any level.

I considered that there might just be a conflict with one of my other patches, but even when changing my build configuration so that only the UberASM stuff gets inserted (and some Lunar Magic necessities), I still can't get anything to happen in the game.

Did I just fail to follow some instructions, or did I run into the weirdest bug ever?

**Comment by Fernap** [comment]
It needs a label: `main:`, `init:`, `end:`, etc.  Naked code like that won't run by itself (it's perfectly fine to start a file with a data table and have the code under `main:` afterwards, e.g.).

**Comment by RPGHacker** [comment]
> Did I just fail to follow some instructions

Of course that's what it is! 🙃
I was so focussed on integrating UberASM Tool into my build system that I completely failed to read anything besides the command line usage guide. 🤦‍♂️

Good to know it was something this simple (I kinda expected that), but also man, I feel stupid now, lol!

**Comment by RPGHacker** [comment]
Well, I already closed the issue, but since we're on this topic: Would it be worth adding a "no label found in resource" error to UberASM Tool? Or are there legitimate use cases for ever doing that (that can't be solved better via a library file)?

**Comment by Fernap** [comment]
Hey no worries...but that's actually a good idea, and should be reasonably easy to add.  It certainly would have caught this right away, and might catch stuff that uses `Main:` instead of `main:` (which some old resources do).

Edit: and no, I can't think of any good reason to permit adding such a thing.

**Comment by Fernap** [comment]
Oh, and a gamemode or overworld resource could just have `load:`, and still insert, even though it also probably shouldn't, but that would be a little more difficult to check for, and probably isn't worth the trouble.
